// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type BlogPost = Collections['blogPosts']['schema']['_output']
export declare const blogPosts: BlogPost[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]
